databases:
  - name: mr-impots-db
    databaseName: mr_impots
    user: mrimpots
    plan: free

services:
  - type: web
    name: mr-impots-web
    env: docker
    plan: free
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: "MrImpots"
      - key: APP_ENV
        value: "production"
      - key: APP_DEBUG
        value: "false"
      - key: TELESCOPE_ENABLED
        value: "true"
      - key: TELESCOPE_ALLOWED_EMAILS
        value: "admin@example.com" # À remplacer par tes emails séparés par des virgules
      - key: FRONTEND_URL
        value: "https://votre-frontend-domaine.com" # À remplacer par le vrai domaine du front-end
      - key: ADMIN_URL
        value: "https://votre-admin-domaine.com" # À remplacer par le vrai domaine de l'admin
      - key: APP_KEY
        sync: false # Vous devrez générer la clé (php artisan key:generate --show) et l'ajouter manuellement dans le dashboard Render
      - key: LOG_CHANNEL
        value: "stderr"
      - key: LOG_STDERR_FORMATTER
        value: "Monolog\\Formatter\\JsonFormatter"
      - key: DB_CONNECTION
        value: "pgsql"
      - key: DB_HOST
        fromDatabase:
          name: mr-impots-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: mr-impots-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: mr-impots-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: mr-impots-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: mr-impots-db
          property: password
      - key: CACHE_STORE
        value: "database"
      - key: SESSION_DRIVER
        value: "database"
      - key: QUEUE_CONNECTION
        value: "database"
